/**
 * install コマンド
 *
 * やること:
 * 1. OSごとのClaude設定ディレクトリを検出
 * 2. ~/.claude/deepseek-claude-usage/ を作成
 * 3. statusLine実行用スクリプトを配置
 * 4. 既存 settings.json を読み込む
 * 5. バックアップを作成
 * 6. statusLine を追加または更新
 * 7. 成功メッセージを表示
 * 8. APIキー設定方法を表示
 * 9. Claude Code再起動を促す
 */
import * as fs from 'fs';
import * as path from 'path';
import {
  getClaudeDir,
  getSettingsPath,
  getToolDir,
  getToolDistDir,
  getStatusLineScriptPath,
  pathExists,
} from '../paths';
import {
  readSettings,
  writeSettings,
  backupSettings,
  hasExistingStatusLine,
  updateStatusLine,
} from '../settings';

export interface InstallOptions {
  force: boolean;
  interactive: boolean;
}

/**
 * パッケージのルートディレクトリを取得
 * npm経由で実行された場合、binスクリプトの位置から逆算
 */
function getPackageRoot(): string {
  // bin/deepseek-claude-usage.js から見て ../../
  // dist/cli.js から見て ../
  // 両方に対応するため、dist/ ディレクトリの位置から探す
  const candidates = [
    path.join(__dirname, '..'),            // src/commands/ → src/ → root
    path.join(__dirname, '..', '..'),      // dist/commands/ → dist/ → root
  ];

  for (const candidate of candidates) {
    const pkgJson = path.join(candidate, 'package.json');
    if (pathExists(pkgJson)) {
      return candidate;
    }
  }

  // 見つからない場合は __dirname から推測
  return path.join(__dirname, '..');
}

/**
 * dist ディレクトリをツールディレクトリにコピー
 */
function copyDistToToolDir(packageRoot: string): void {
  const toolDir = getToolDir();
  const toolDistDir = getToolDistDir();

  // ツールディレクトリを作成
  if (!pathExists(toolDir)) {
    fs.mkdirSync(toolDir, { recursive: true });
  }

  // 既存のdistを削除
  if (pathExists(toolDistDir)) {
    fs.rmSync(toolDistDir, { recursive: true, force: true });
  }

  // distディレクトリを探す（ビルド済みの場合）
  const srcDist = path.join(packageRoot, 'dist');
  if (!pathExists(srcDist)) {
    throw new Error(
      `Built files not found at ${srcDist}.\n` +
      `Please run 'npm run build' first or install from npm.`
    );
  }

  // distをコピー
  copyDirectory(srcDist, toolDistDir);
}

/**
 * ディレクトリを再帰的にコピー
 */
function copyDirectory(src: string, dest: string): void {
  fs.mkdirSync(dest, { recursive: true });

  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDirectory(srcPath, destPath);
    } else if (entry.isFile()) {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * statusLineラッパースクリプトを作成
 *
 * このスクリプトは ~/.claude/deepseek-claude-usage/statusline.js に配置され、
 * Claude Code から node で直接実行される。
 * require('./dist/statusline') でコピー済みのdistからモジュールを読み込む。
 */
function createStatusLineScript(): void {
  const scriptPath = getStatusLineScriptPath();

  // ラッパースクリプト（CJS）
  const scriptContent = `#!/usr/bin/env node
/**
 * deepseek-claude-usage statusLine script
 * Claude Code statusLine から呼び出されます
 * Auto-generated by deepseek-claude-usage install
 */
'use strict';
const path = require('path');
const distDir = path.join(__dirname, 'dist');

try {
  const { main } = require(path.join(distDir, 'statusline.js'));
  main().catch(() => {
    process.stdout.write('DS error');
  });
} catch (err) {
  // モジュール読み込みエラー時も最低限の表示を返す
  process.stdout.write('DS err: ' + (err.message || ''));
}
`;

  fs.writeFileSync(scriptPath, scriptContent, 'utf-8');

  // 実行権限を設定（POSIX環境）
  try {
    fs.chmodSync(scriptPath, 0o755);
  } catch {
    // Windows等で権限設定ができなくても続行
  }
}

/**
 * install コマンドのメイン処理
 */
export async function install(options: InstallOptions): Promise<void> {
  const { force, interactive } = options;

  // 1. 前提チェック
  const claudeDir = getClaudeDir();
  console.log(`Claude settings directory: ${claudeDir}`);

  // 2. 既存 settings.json を読み込み
  const settingsPath = getSettingsPath();
  let existingSettings;
  try {
    existingSettings = readSettings();
  } catch (err) {
    console.error(`\n❌ Error reading settings.json:`);
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }

  // 3. 既存のstatusLineがある場合の処理
  if (hasExistingStatusLine(existingSettings.settings) && !force) {
    const existingStatusLine = existingSettings.settings.statusLine;
    console.log('\n⚠️  Existing statusLine configuration detected:');
    console.log(`   type: ${existingStatusLine?.type}`);
    console.log(`   command: ${existingStatusLine?.command}`);

    if (!interactive) {
      console.log('\n❌ Cannot overwrite existing statusLine in non-interactive mode.');
      console.log('   Use --force to overwrite, or manually edit settings.json first.');
      process.exit(1);
    }

    // 対話環境では確認（実際には process.stdin での確認だが、
    // MVPでは --force がない限り上書きしない方針を明確に示す）
    console.log('\n💡 To overwrite, use: npx deepseek-claude-usage install --force');
    console.log('   A backup will be created before overwriting.');
    process.exit(0);
  }

  // 4. バックアップを作成
  if (pathExists(settingsPath)) {
    const backupPath = backupSettings();
    if (backupPath) {
      console.log(`\n📦 Backup created: ${backupPath}`);
    }
  }

  // 5. distファイルをツールディレクトリにコピー
  const packageRoot = getPackageRoot();
  console.log(`\n📋 Copying files to ${getToolDir()}...`);
  copyDistToToolDir(packageRoot);

  // 6. statusLineラッパースクリプトを作成
  createStatusLineScript();
  console.log(`📝 StatusLine script: ${getStatusLineScriptPath()}`);

  // 7. settings.json の statusLine を更新
  const statusLineScriptPath = getStatusLineScriptPath();
  const newSettings = updateStatusLine(
    existingSettings.settings,
    `node "${statusLineScriptPath}"`,
    30
  );
  writeSettings(newSettings);

  // 8. 成功メッセージ
  console.log(`\n✅ deepseek-claude-usage installed!\n`);
  console.log(`Claude Code statusLine is now configured.\n`);
  console.log(`Set your DeepSeek API key:\n`);
  console.log(`macOS/Linux:`);
  console.log(`  export DEEPSEEK_API_KEY="sk-xxxx"\n`);
  console.log(`Windows PowerShell:`);
  console.log(`  $env:DEEPSEEK_API_KEY="sk-xxxx"\n`);
  console.log(`Windows Command Prompt:`);
  console.log(`  setx DEEPSEEK_API_KEY "sk-xxxx"\n`);
  console.log(`Then restart Claude Code.`);
}

/**
 * コマンドライン引数からInstallOptionsを抽出
 */
export function parseInstallArgs(args: string[]): InstallOptions {
  const force = args.includes('--force') || args.includes('-f');
  // npm経由の場合は非対話的とみなす（CI等を考慮）
  const interactive = process.stdin.isTTY && !force;

  return { force, interactive };
}
